FROM python:3.13

WORKDIR /pipeline/orchestration

COPY stores/ /pipeline/stores/
COPY dbt_billigaste_kvittot/ /pipeline/dbt_billigaste_kvittot/
COPY orchestration/ /pipeline/orchestration/

RUN pip install dagster dagster-dbt dagster-dlt dagster-webserver dbt-core dbt-duckdb dlt duckdb

CMD ["dagster", "dev", "-f", "definitions.py", "-h", "0.0.0.0", "-p", "3000"]
